# Site
name: 'Guest Book Club'
description: 'The blog is dedicated to guest books. It includes product recommendations, the most creative guest books ideas, DIY tutorials and much more!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'guestbookclub.com'
email: 'stargoodsamazon@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Thomas:
      name:           Thomas
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar.png
      bio:            "Hi, I am Thomas, the author of Guest Book Club! I share things like product recommendations, the most creative guest books ideas, DIY tutorials and much more!"
      email:          stargoodsamazon@gmail.com
      twitter:        https://twitter.com/ThomasLech11

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Thomas
      avatar: assets/images/avatar.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]